### ISSUE TITLE
"can't parse '#{stackframe}' (please file an issue so we can fix " \

### ISSUE THREAD

**Issue by Schwad** [airbrake/airbrake-ruby#103]
I got this particular error which led me here, I am filing an issue because the code asked to!

I ended up finding the error that broke airbrake, working in CoffeeScript with better errors that error kept popping up. 

I found the problem, my JS tendencies had popped up and I had assigned `var x = []` instead of `x = []`, causing this error to pop up. 

Thanks!

**Comment by kyrylo** [comment]
Hah, thanks! That said, it should have printed the frame it couldn't parse. Without an example backtrace (or frame), I'm afraid, we cannot add proper support. That said, airbrake-ruby should work just fine, because we don't raise the error, but log it.

**Comment by kyrylo** [comment]
Just to be clear, if you have an example of that backtrace (or individual frame at least), which couldn't be parsed, I'd be happy to fix the issue. If not, let's close this, since I cannot do much here without it.

**Comment by Schwad** [comment]
Gonna replicate this and bring it back up for you momentarily. 😃

**Comment by Schwad** [comment]
`can't parse 'apply.bare (<anonymous>:6:21)'`

**Comment by Schwad** [comment]
```
Airbrake::Error - can't parse 'apply.bare (<anonymous>:6:21)':
  airbrake-ruby (1.4.3) lib/airbrake-ruby/backtrace.rb:93:in `match_frame'
  airbrake-ruby (1.4.3) lib/airbrake-ruby/backtrace.rb:63:in `block in parse'
  airbrake-ruby (1.4.3) lib/airbrake-ruby/backtrace.rb:62:in `parse'
  airbrake-ruby (1.4.3) lib/airbrake-ruby/nested_exception.rb:19:in `block in as_json'
  airbrake-ruby (1.4.3) lib/airbrake-ruby/nested_exception.rb:16:in `as_json'
  airbrake-ruby (1.4.3) lib/airbrake-ruby/notice.rb:63:in `initialize'
  airbrake-ruby (1.4.3) lib/airbrake-ruby/notifier.rb:108:in `build_notice'
  airbrake-ruby (1.4.3) lib/airbrake-ruby.rb:283:in `call_notifier'
  airbrake-ruby (1.4.3) lib/airbrake-ruby.rb:239:in `build_notice'
  airbrake (5.4.0) lib/airbrake/rack/notice_builder.rb:42:in `build_notice'
  airbrake (5.4.0) lib/airbrake/rack/middleware.rb:38:in `notify_airbrake'
  airbrake (5.4.0) lib/airbrake/rack/middleware.rb:24:in `rescue in call'
  airbrake (5.4.0) lib/airbrake/rack/middleware.rb:21:in `call'
  better_errors (2.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  rack-mini-profiler (0.9.3) lib/mini_profiler/profiler.rb:276:in `call'
  railties (4.2.7) lib/rails/engine.rb:518:in `call'
  railties (4.2.7) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/nickschwaderer/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/nickschwaderer/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/nickschwaderer/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by Schwad** [comment]
To create this error I changed `x = []` to `var x = []` in coffee.

**Comment by kyrylo** [comment]
Thanks! What's your airbrake-ruby version? We don't raise `Airbrake::Error` there anymore in this situation. Instead, the error is logged (it still can't be parsed, we simply became less aggressive about it).

**Comment by Schwad** [comment]
Oh crap. I may be in the wrong repo. We're running `'airbrake'` not `'airbrake-ruby'`, we're on `'~> 5.2'`,  is it possible we're in need of an update? :grin:

**Comment by kyrylo** [comment]
You're good in terms of library selection. `airbrake` depends on `airbrake-ruby` :)
Updating it would definitely be the right call. Current `airbrake` version is `v5.4.2`. Current `airbrake-ruby` version is `v1.4.4`. Make sure to update both :)

**Comment by Schwad** [comment]
Thank you! :) 💯
