### ISSUE TITLE
Can't alloc thread

### ISSUE THREAD

**Issue by benoittgt** [airbrake/airbrake-ruby#367]
This has been posted also here : https://github.com/mperham/sidekiq/issues/4029

```
13:29:02.713804+00:00 app worker_notifications.1 - - 4 TID-1u06zw SendNotificationsWorker JID-754eb57d86009b5a6baee320 INFO: SidekiqMemorySampling queue=notifications worker=SendNotificationsWorker jid=754eb57d86009b5a6baee320 
13:29:02.719922+00:00 app worker_notifications.1 - - 4 TID-1u06no SendNotificationsWorker JID-fdd856cc57c54585cd4aab19 INFO: SidekiqMemorySampling queue=notifications worker=SendNotificationsWorker jid=fdd856cc57c54585cd4aab19 
13:29:02.727448+00:00 app worker_notifications.1 - - 4 TID-1u06zw WARN: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
13:29:02.727736+00:00 app worker_notifications.1 - - 4 TID-1u06zw WARN: {"context":"processor"}
13:29:02.727917+00:00 app worker_notifications.1 - - 4 TID-1u06zw WARN: ThreadError: can't alloc thread
13:29:02.728000+00:00 app worker_notifications.1 - - 4 TID-1u06zw WARN: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `new'
13:29:02.728003+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `safe_thread'
13:29:02.728004+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:65:in `start'
13:29:02.728005+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:96:in `block in processor_died'
13:29:02.728007+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `synchronize'
13:29:02.728008+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `processor_died'
13:29:02.728009+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:79:in `rescue in run'
13:29:02.728010+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:70:in `run'
13:29:02.728012+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
13:29:02.728013+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
13:29:02.728151+00:00 app worker_notifications.1 - - W, [2018-11-28T13:29:02.728053 #4] WARN -- : **Airbrake: falling back to sync delivery because there are no running async workers
13:29:02.728239+00:00 app worker_notifications.1 - - 4 TID-1u06zw ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
13:29:02.728289+00:00 app worker_notifications.1 - - 4 TID-1u06zw ERROR: attempted to build can't alloc thread with closed Airbrake instance
13:29:02.728369+00:00 app worker_notifications.1 - - 4 TID-1u06zw ERROR: /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby/notifier.rb:59:in `build_notice'
13:29:02.728371+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby/notifier.rb:117:in `send_notice'
13:29:02.728372+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby/notifier.rb:43:in `notify'
13:29:02.728374+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby.rb:199:in `notify'
13:29:02.728375+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/airbrake-7.3.3/lib/airbrake/sidekiq.rb:19:in `notify_airbrake'
13:29:02.728377+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:20:in `call'
13:29:02.728378+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:20:in `block in handle_exception'
13:29:02.728379+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:18:in `each'
13:29:02.728380+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/exception_handler.rb:18:in `handle_exception'
13:29:02.728382+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:18:in `rescue in watchdog'
13:29:02.728383+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:15:in `watchdog'
13:29:02.728384+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
13:29:02.729120+00:00 app worker_notifications.1 - - #<Thread:0x000000000d374ad0@/app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23 aborting> terminated with exception (report_on_exception is true):
28 Nov 2018 14:29:02.991225 <190>1 2018-11-28T13:29:02.729212+00:00 app worker_notifications.1 - - /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `new': can't alloc thread (ThreadError)
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:23:in `safe_thread'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:65:in `start'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:96:in `block in processor_died'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `synchronize'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/manager.rb:91:in `processor_died'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:79:in `rescue in run'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:70:in `run'
	from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
from /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

I found this comment https://github.com/mperham/sidekiq/issues/2732#issuecomment-166706814 but we don't have complicated custom initializer with Redis. For the moment I am not able to find where this could happen. When we go on `/app/vendor/bundle/ruby/2.5.0/gems/airbrake-ruby-2.10.0/lib/airbrake-ruby/notifier.rb:59:in `build_notice'` https://github.com/airbrake/airbrake-ruby/blob/v2.10.0/lib/airbrake-ruby/notifier.rb#L59 we only raise an error.

We don't have a peak of threads or memory in NewRelic. 
![screenshot 2018-11-28 at 15 58 40](https://user-images.githubusercontent.com/8417720/49160299-c5f0ce80-f326-11e8-974c-8e648400f251.png)

![screenshot 2018-11-28 at 16 04 13](https://user-images.githubusercontent.com/8417720/49160562-5202f600-f327-11e8-88f0-36cbd42e4b58.png)

We are on a standard-2x Heroku dyno with 512 threads available.

```ruby
require 'sidekiq'

Sidekiq.configure_client do |config|
  config.redis = { url: ***, size: (ENV['SIDEKIQ_REDIS_CLIENT_SIZE'] || 1) }
  config.error_handlers << proc { |ex, ctx_hash| Airbrake.notify(ex, ctx_hash) }
end

Sidekiq::Client.reliable_push! unless Rails.env.test?

Sidekiq::Extensions.enable_delay!

Sidekiq.logger.level = Logger::WARN if Rails.env.test?

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
  config.server_middleware do |chain|
    chain.add Sidekiq::MemorySamplingMiddleware
    chain.add Sidekiq::RetryMonitoringMiddleware
    chain.add Sidekiq::ExceptionMonitoringMiddleware
  end
end
```

Do you have any ideas of what could happen?

**Comment by kyrylo** [comment]
Out of curiosity, does the standard Airbrake integration with Sidekiq not work for you? 
https://github.com/airbrake/airbrake#sidekiq

If you find it lacking, I'd rather patch it with what it needs, so you don't have to bother with manual configuration.

---

This sounds like a thread leakage but we haven't touched any thread-related code for many releases now. Up until now I've never heard anyone experiencing this error with Airbrake, which makes me think we're not the culprit. That said, you never know, when it comes to threads.

* What's in your Airbrake config?
* Has this been an issue due to an airbrake-ruby upgrade? 
* Or did it start happening only recently and you didn't upgrade airbrake-ruby?

You can temporarily switch your error handler to `Airbrake.notify_sync`, to eliminate one possible problem. If it happens even with `notify_sync`, then it's a good sign that Airbrake is not to blame.

**Comment by benoittgt** [comment]
Sorry. We didn't take time to work on it. We will reopen it if we find something.

Thanks for the support.
